controller_list:
#-------------for gazebo UR5-------------------------------
  - name: "arm_controller"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - simple_arm_shoulder_pan_joint
      - simple_arm_shoulder_lift_joint
      - simple_arm_elbow_joint
      - simple_arm_wrist_1_joint
      - simple_arm_wrist_2_joint
      - simple_arm_wrist_3_joint
#-------------for gazebo gripper---------------------------
  - name: "gripper"
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - simple_gripper_robotiq_85_left_knuckle_joint
